import { Injectable } from '@nestjs/common';
import type { TrackerRepository } from '../../../domain/tracker/tracker-repository.port';
import { TrackerService } from '../../../tracker/tracker.service';

@Injectable()
export class LegacyTrackerRepository implements TrackerRepository {
  constructor(private readonly service: TrackerService) {}
  profile(accountId: string) { return this.service.profile(accountId); } updateProfile(accountId: string, data: object, correlationId: string) { return this.service.updateProfile(accountId, data as never, correlationId); }
  listTasks(accountId: string) { return this.service.listTasks(accountId); } createTask(accountId: string, data: object, correlationId: string) { return this.service.createTask(accountId, data as never, correlationId); } updateTask(accountId: string, id: string, data: object, correlationId: string) { return this.service.updateTask(accountId, id, data as never, correlationId); } deleteTask(accountId: string, id: string, correlationId: string) { return this.service.deleteTask(accountId, id, correlationId); }
  listHabits(accountId: string) { return this.service.listHabits(accountId); } createHabit(accountId: string, data: object, correlationId: string) { return this.service.createHabit(accountId, data as never, correlationId); } updateHabit(accountId: string, id: string, data: object, correlationId: string) { return this.service.updateHabit(accountId, id, data as never, correlationId); } deleteHabit(accountId: string, id: string, correlationId: string) { return this.service.deleteHabit(accountId, id, correlationId); } checkInHabit(accountId: string, id: string, date: string, correlationId: string) { return this.service.checkInHabit(accountId, id, date, correlationId); }
  listWorkouts(accountId: string) { return this.service.listWorkouts(accountId); } createWorkout(accountId: string, data: object, correlationId: string) { return this.service.createWorkout(accountId, data as never, correlationId); } updateWorkout(accountId: string, id: string, data: object, correlationId: string) { return this.service.updateWorkout(accountId, id, data as never, correlationId); } deleteWorkout(accountId: string, id: string, correlationId: string) { return this.service.deleteWorkout(accountId, id, correlationId); }
  listFoods(accountId: string) { return this.service.listFoods(accountId); } createFood(accountId: string, data: object, correlationId: string) { return this.service.createFood(accountId, data as never, correlationId); } updateFood(accountId: string, id: string, data: object, correlationId: string) { return this.service.updateFood(accountId, id, data as never, correlationId); } deleteFood(accountId: string, id: string, correlationId: string) { return this.service.deleteFood(accountId, id, correlationId); } dashboard(accountId: string) { return this.service.dashboard(accountId); }
}
