import { type FormEvent, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { useAppStore } from '../../app/store';
import { sections, type Section } from '../../entities/navigation';
import { apiRequest } from '../../shared/api/http-client';
import { foodSchema, habitSchema, profileSchema, taskSchema, workoutSchema } from './schemas';

export function Workspace({ session, preview, onSignOut }: { session: Session; preview: boolean; onSignOut: () => void }) {
  const section = useAppStore((state) => state.section); const setSection = useAppStore((state) => state.setSection);
  return <main className="workspace"><aside><a className="brand" href="#today">itsunikki</a><nav aria-label="Workspace">{sections.map((item) => <button key={item} className={item === section ? 'nav-current' : ''} onClick={() => setSection(item)}>{item}</button>)}</nav><button className="text-button signout" onClick={onSignOut}>Sign out</button></aside><section className="content"><header><div><p className="eyebrow">Personal workspace</p><h1>{section}</h1></div><p className="account">{session.user.email}</p></header>{preview && <p className="banner" role="status">Preview mode: sign-in and tracker data are available only with your local NestJS API.</p>}<SectionContent section={section} token={session.access_token} /></section><nav className="mobile-nav" aria-label="Workspace">{sections.slice(0, 5).map((item) => <button key={item} aria-current={item === section ? 'page' : undefined} onClick={() => setSection(item)}>{item}</button>)}</nav></main>;
}

function SectionContent({ section, token }: { section: Section; token: string }) {
  const config: Record<Exclude<Section, 'Today' | 'Review' | 'Settings'>, { endpoint: string; title: string; fields: string[] }> = { Tasks: { endpoint: '/tasks', title: 'Add a task', fields: ['title', 'dueDate'] }, Habits: { endpoint: '/habits', title: 'Add a habit', fields: ['name', 'target'] }, Workouts: { endpoint: '/workouts', title: 'Log a workout', fields: ['activity', 'durationMinutes'] }, Nutrition: { endpoint: '/foods', title: 'Add food entry', fields: ['name', 'kcal'] } };
  if (section === 'Today') return <EmptyState title="Nothing needs your attention yet." body="When you add a task, habit, workout, or food entry, today’s progress will appear here." />;
  if (section === 'Review') return <EmptyState title="Your history will build here." body="Choose a day or week once you have saved records to review." />;
  if (section === 'Settings') return <ProfileForm token={token} />;
  const current = config[section]; return <EntryForm {...current} token={token} />;
}
function EmptyState({ title, body }: { title: string; body: string }) { return <section className="empty-state"><h2>{title}</h2><p>{body}</p></section>; }
function ProfileForm({ token }: { token: string }) { const setNotice = useAppStore((state) => state.setNotice); const notice = useAppStore((state) => state.notice); const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone); async function submit(event: FormEvent) { event.preventDefault(); try { const data = profileSchema.parse({ timezone }); await apiRequest('/profile', token, { method: 'PATCH', body: JSON.stringify(data) }); setNotice('Timezone saved. Future daily boundaries use this setting.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not save timezone.'); } } return <section className="form-panel"><h2>Profile settings</h2><p>Your timezone defines due dates, daily totals, and history boundaries.</p><form onSubmit={submit}><label>Timezone<input value={timezone} onChange={(event) => setTimezone(event.target.value)} required /></label><button>Save timezone</button></form>{notice && <p role="status" className="notice">{notice}</p>}</section>; }
function EntryForm({ title, endpoint, fields, token }: { title: string; endpoint: string; fields: string[]; token: string }) { const setNotice = useAppStore((state) => state.setNotice); const notice = useAppStore((state) => state.notice); const [values, setValues] = useState<Record<string, string>>({}); async function submit(event: FormEvent) { event.preventDefault(); try { const now = new Date().toISOString(); const raw: Record<string, unknown> = endpoint === '/tasks' ? { title: values.title, dueDate: values.dueDate, recurrence: 'none' } : endpoint === '/habits' ? { name: values.name, target: Number(values.target), frequency: 'daily' } : endpoint === '/workouts' ? { activity: values.activity, durationMinutes: Number(values.durationMinutes), performedAt: now } : { name: values.name, kcal: Number(values.kcal), carbohydrates: 0, fat: 0, protein: 0, meal: 'snack', occurredAt: now }; const data = endpoint === '/tasks' ? taskSchema.parse(raw) : endpoint === '/habits' ? habitSchema.parse(raw) : endpoint === '/workouts' ? workoutSchema.parse(raw) : foodSchema.parse(raw); await apiRequest(endpoint, token, { method: 'POST', body: JSON.stringify(data) }); setValues({}); setNotice('Saved. Your dashboard will refresh when it loads data.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not save this entry.'); } } return <section className="form-panel"><h2>{title}</h2><p>Saved records stay private to your account.</p><form onSubmit={submit}>{fields.map((field) => <label key={field}>{field === 'dueDate' ? 'Due date' : field === 'durationMinutes' ? 'Minutes' : field[0].toUpperCase() + field.slice(1)}<input type={field === 'dueDate' ? 'datetime-local' : field === 'target' || field === 'durationMinutes' || field === 'kcal' ? 'number' : 'text'} min={field === 'target' || field === 'durationMinutes' || field === 'kcal' ? 0 : undefined} value={values[field] ?? ''} onChange={(event) => setValues({ ...values, [field]: event.target.value })} required /></label>)}<button>Save entry</button></form>{notice && <p role="status" className="notice">{notice}</p>}</section>; }
