import { sql } from 'drizzle-orm';
import { boolean, check, date, integer, jsonb, pgSchema, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';

export const tracker = pgSchema('tracker');
const timestamps = { createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() };

export const profiles = tracker.table('profiles', { accountId: uuid('account_id').primaryKey().notNull(), timezone: varchar('timezone', { length: 64 }).notNull(), ...timestamps });
export const tasks = tracker.table('tasks', { id: uuid('id').primaryKey().notNull().defaultRandom(), accountId: uuid('account_id').notNull(), title: varchar('title', { length: 160 }).notNull(), dueDate: timestamp('due_date', { withTimezone: true }).notNull(), recurrence: varchar('recurrence', { length: 16 }).notNull().default('none'), completed: boolean('completed').notNull().default(false), ...timestamps }, (t) => [check('tasks_recurrence_check', sql`${t.recurrence} IN ('none', 'daily', 'weekly')`)]);
export const habits = tracker.table('habits', { id: uuid('id').primaryKey().notNull().defaultRandom(), accountId: uuid('account_id').notNull(), name: varchar('name', { length: 120 }).notNull(), target: integer('target').notNull().default(1), frequency: varchar('frequency', { length: 16 }).notNull(), checkIns: date('check_ins').array().notNull().default(sql`ARRAY[]::date[]`), ...timestamps }, (t) => [check('habits_target_check', sql`${t.target} >= 1`), check('habits_frequency_check', sql`${t.frequency} IN ('daily', 'weekly')`)]);
export const workouts = tracker.table('workouts', { id: uuid('id').primaryKey().notNull().defaultRandom(), accountId: uuid('account_id').notNull(), activity: varchar('activity', { length: 120 }).notNull(), performedAt: timestamp('performed_at', { withTimezone: true }).notNull(), durationMinutes: integer('duration_minutes').notNull(), metrics: jsonb('metrics').$type<Record<string, number>>().notNull().default(sql`'{}'::jsonb`), ...timestamps }, (t) => [check('workouts_duration_check', sql`${t.durationMinutes} >= 0`)]);
export const foodEntries = tracker.table('food_entries', { id: uuid('id').primaryKey().notNull().defaultRandom(), accountId: uuid('account_id').notNull(), name: varchar('name', { length: 160 }).notNull(), meal: varchar('meal', { length: 16 }).notNull(), kcal: integer('kcal').notNull(), carbohydrates: integer('carbohydrates').notNull(), fat: integer('fat').notNull(), protein: integer('protein').notNull(), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(), metrics: jsonb('metrics').$type<Record<string, number>>().notNull().default(sql`'{}'::jsonb`), ...timestamps }, (t) => [check('food_entries_meal_check', sql`${t.meal} IN ('breakfast', 'lunch', 'dinner', 'snack')`), check('food_entries_values_check', sql`${t.kcal} >= 0 AND ${t.carbohydrates} >= 0 AND ${t.fat} >= 0 AND ${t.protein} >= 0`)]);
export const auditEvents = tracker.table('audit_events', { id: uuid('id').primaryKey().notNull().defaultRandom(), actorId: uuid('actor_id').notNull(), action: varchar('action', { length: 80 }).notNull(), resourceType: varchar('resource_type', { length: 40 }).notNull(), resourceId: varchar('resource_id', { length: 64 }).notNull(), outcome: varchar('outcome', { length: 16 }).notNull(), correlationId: varchar('correlation_id', { length: 128 }).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (t) => [check('audit_events_outcome_check', sql`${t.outcome} IN ('accepted', 'denied')`)]);
export const schema = { profiles, tasks, habits, workouts, foodEntries, auditEvents };
